from pathlib import Path


def patch_file(path_s, replacements):
    path = Path(path_s)
    text = path.read_text(encoding='utf-8')
    for label, old, new in replacements:
        count = text.count(old)
        expected = 2 if label == 'restore account compromise rows' else 1
        if count != expected:
            raise SystemExit(f'{path_s} {label}: expected exactly {expected} match(es), got {count}')
        text = text.replace(old, new, 1)
        print('patched', path_s, label)
    path.write_text(text, encoding='utf-8')

patch_file('app/src/main/java/eu/faircode/email/AliasCompromiseReviewStore.java', [
    ('account prefix and reversible mark',
'''    public static void markReviewedHealthy(Context context, EntityAlias alias) {\n        if (context == null || alias == null || alias.account_uuid == null || alias.address == null)\n            return;\n        EntitySpamMeta meta = new EntitySpamMeta();\n        meta.key = key(alias.account_uuid, alias.address);\n        meta.long_value = (long) (alias.spam_hits == null ? 0 : alias.spam_hits);\n        SpamIntelligenceDB.getInstance(context).alias().putMeta(meta);\n    }\n\n    public static String globalMetaPrefix() {\n        return PREFIX;\n    }''',
'''    public static boolean markReviewedHealthy(Context context, EntityAlias alias) {\n        if (context == null || alias == null || alias.account_uuid == null || alias.address == null)\n            return false;\n        DaoAlias dao = SpamIntelligenceDB.getInstance(context).alias();\n        String metaKey = key(alias.account_uuid, alias.address);\n        long currentSpam = alias.spam_hits == null ? 0L : alias.spam_hits;\n        Long previous = dao.getMetaLong(metaKey);\n        if (previous != null && previous == currentSpam)\n            return false;\n        EntitySpamMeta meta = new EntitySpamMeta();\n        meta.key = metaKey;\n        meta.long_value = currentSpam;\n        dao.putMeta(meta);\n        return true;\n    }\n\n    public static String accountMetaPrefix(String accountUuid) {\n        if (accountUuid == null)\n            return PREFIX;\n        return PREFIX + accountUuid.trim() + ":";\n    }\n\n    public static String globalMetaPrefix() {\n        return PREFIX;\n    }''')
])

patch_file('app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java', [
    ('capture account compromise meta',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n\n                if (messageId > 0) {''',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n                root.put("compromise_meta", metaToJson(dao.getMetaByPrefix(\n                        AliasCompromiseReviewStore.accountMetaPrefix(account))));\n\n                if (messageId > 0) {'''),
    ('capture full account compromise meta',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n\n                JSONArray deliveries = new JSONArray();''',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n                root.put("compromise_meta", metaToJson(dao.getMetaByPrefix(\n                        AliasCompromiseReviewStore.accountMetaPrefix(account))));\n\n                JSONArray deliveries = new JSONArray();'''),
    ('capture global compromise meta',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.globalMetaPrefix())));\n\n                JSONArray deliveries = new JSONArray();''',
'''                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.globalMetaPrefix())));\n                root.put("compromise_meta", metaToJson(dao.getMetaByPrefix(\n                        AliasCompromiseReviewStore.globalMetaPrefix())));\n\n                JSONArray deliveries = new JSONArray();'''),
    ('restore account delete compromise meta',
'''                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.accountMetaPrefix(account));\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));''',
'''                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.accountMetaPrefix(account));\n                    if (root.has("compromise_meta"))\n                        dao.deleteMetaByPrefix(AliasCompromiseReviewStore.accountMetaPrefix(account));\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));'''),
    ('restore account compromise rows',
'''                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    if (!families.isEmpty())''',
'''                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    List<EntitySpamMeta> compromiseMeta = root.has("compromise_meta")\n                            ? metaFromJson(root.getJSONArray("compromise_meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    if (!families.isEmpty())'''),
    ('restore account put compromise rows',
'''                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n\n                    if (root.optBoolean("full_account_learning", false)) {''',
'''                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n                    if (!compromiseMeta.isEmpty())\n                        dao.putMeta(compromiseMeta);\n\n                    if (root.optBoolean("full_account_learning", false)) {'''),
    ('restore global delete compromise meta',
'''                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                    dao.resetAllDeliveryLearning();''',
'''                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                    if (root.has("compromise_meta"))\n                        dao.deleteMetaByPrefix(AliasCompromiseReviewStore.globalMetaPrefix());\n                    dao.resetAllDeliveryLearning();'''),
    ('restore global compromise rows',
'''                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    if (!families.isEmpty())''',
'''                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    List<EntitySpamMeta> compromiseMeta = root.has("compromise_meta")\n                            ? metaFromJson(root.getJSONArray("compromise_meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    if (!families.isEmpty())'''),
    ('restore global put compromise rows',
'''                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n\n                    JSONArray deliveries = root.getJSONArray("deliveries");''',
'''                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n                    if (!compromiseMeta.isEmpty())\n                        dao.putMeta(compromiseMeta);\n\n                    JSONArray deliveries = root.getJSONArray("deliveries");'''),
    ('reset compromise meta',
'''                dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                dao.resetAllDeliveryLearning();''',
'''                dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                dao.deleteMetaByPrefix(AliasCompromiseReviewStore.globalMetaPrefix());\n                dao.resetAllDeliveryLearning();''')
])

patch_file('app/src/main/java/eu/faircode/email/SpamUndoManager.java', [
    ('alias action constants',
'''    public static final String ACTION_RENAME = "RENAME";\n    public static final String ACTION_RESET_ALL = "RESET_ALL";''',
'''    public static final String ACTION_RENAME = "RENAME";\n    public static final String ACTION_ALIAS_KEEP_ACTIVE = "ALIAS_KEEP_ACTIVE";\n    public static final String ACTION_ALIAS_COMPROMISED = "ALIAS_COMPROMISED";\n    public static final String ACTION_RESET_ALL = "RESET_ALL";'''),
    ('generic account action',
'''    public static boolean renameFamily(Context context,''',
'''    public static boolean runAccountAction(\n            Context context,\n            String accountUuid,\n            String action,\n            String description,\n            Callable<Boolean> delegate) {\n        if (context == null || accountUuid == null || accountUuid.trim().isEmpty() || delegate == null)\n            return false;\n\n        Context app = context.getApplicationContext();\n        SpamIntelligenceDB db = SpamIntelligenceDB.getInstance(app);\n        Long historyId = null;\n        try {\n            String before = SpamLearningSnapshot.captureAccountAllLearning(\n                    app, accountUuid.trim());\n            historyId = recordBefore(db, accountUuid.trim(), null,\n                    0L, action, description, before);\n            Boolean changed = delegate.call();\n            if (!Boolean.TRUE.equals(changed)) {\n                db.actions().delete(historyId);\n                return false;\n            }\n            return true;\n        } catch (Throwable ex) {\n            Log.e(ex);\n            if (historyId != null)\n                db.actions().delete(historyId);\n            return false;\n        }\n    }\n\n    public static boolean renameFamily(Context context,''')
])

patch_file('app/src/main/java/eu/faircode/email/ActivitySpamControl.java', [
    ('undoable compromise dialog',
'''        new AlertDialog.Builder(this)\n                .setTitle("Er aliaset kompromittert?")\n                .setMessage(alias.address + "\\n\\nSpam er bekreftet, men det er ikke nok alene til å konkludere med at aliasadressen har lekket.")\n                .setNegativeButton("Behold aktivt", (d, w) -> {\n                    AliasCompromiseReviewStore.markReviewedHealthy(getApplicationContext(), alias);\n                    tvStatus.setText("Aliaset beholdes aktivt. Ny spam-evidens kan åpne spørsmålet igjen.");\n                    renderCurrent();\n                })\n                .setPositiveButton("Marker kompromittert", (d, w) -> {\n                    executor.execute(() -> {\n                        DaoAlias dao = SpamIntelligenceDB.getInstance(getApplicationContext()).alias();\n                        int changed = dao.markCompromised(alias.account_uuid, alias.address);\n                        runOnUiThread(() -> {\n                            tvStatus.setText(changed > 0 ? "Alias markert kompromittert." : "Aliasstatus var allerede oppdatert.");\n                            renderCurrent();\n                        });\n                    });\n                })\n                .show();''',
'''        new AlertDialog.Builder(this)\n                .setTitle("Er aliaset kompromittert?")\n                .setMessage(alias.address + "\\n\\nSpam er bekreftet, men det er ikke nok alene til å konkludere med at aliasadressen har lekket.")\n                .setNegativeButton("Behold aktivt", (d, w) -> executor.execute(() -> {\n                    boolean changed = SpamUndoManager.runAccountAction(\n                            getApplicationContext(), alias.account_uuid,\n                            SpamUndoManager.ACTION_ALIAS_KEEP_ACTIVE,\n                            "Behold alias aktivt",\n                            () -> AliasCompromiseReviewStore.markReviewedHealthy(\n                                    getApplicationContext(), alias));\n                    runOnUiThread(() -> {\n                        tvStatus.setText(changed\n                                ? "Aliaset beholdes aktivt. Ny spam-evidens kan åpne spørsmålet igjen."\n                                : "Aliaset var allerede vurdert som aktivt.");\n                        if (changed)\n                            Snackbar.make(svContent, "Alias beholdt aktivt.", Snackbar.LENGTH_LONG)\n                                    .setAction("ANGRE", v -> undoLatest()).show();\n                        loadDashboardExtras(selectedAccount);\n                        renderCurrent();\n                    });\n                }))\n                .setPositiveButton("Marker kompromittert", (d, w) -> executor.execute(() -> {\n                    boolean changed = SpamUndoManager.runAccountAction(\n                            getApplicationContext(), alias.account_uuid,\n                            SpamUndoManager.ACTION_ALIAS_COMPROMISED,\n                            "Marker alias kompromittert",\n                            () -> SpamIntelligenceDB.getInstance(getApplicationContext()).alias()\n                                    .markCompromised(alias.account_uuid, alias.address) > 0);\n                    runOnUiThread(() -> {\n                        tvStatus.setText(changed\n                                ? "Alias markert kompromittert."\n                                : "Aliasstatus var allerede oppdatert.");\n                        if (changed)\n                            Snackbar.make(svContent, "Alias markert kompromittert.", Snackbar.LENGTH_LONG)\n                                    .setAction("ANGRE", v -> undoLatest()).show();\n                        loadDashboardExtras(selectedAccount);\n                        renderCurrent();\n                    });\n                }))\n                .show();''')
])

print('alias decision undo patch complete')
