from pathlib import Path

P = Path('app/src/main/java/eu/faircode/email/SpamIntelligence.java')
text = P.read_text()


def once(old, new, label):
    global text
    c = text.count(old)
    if c != 1:
        raise SystemExit(f'{label}: expected 1 match, got {c}')
    text = text.replace(old, new, 1)

once('''            if (folder == null || message == null || message.account == null ||\n                    message.deliveredto == null)\n                return;\n''','''            if (folder == null || message == null || message.account == null)\n                return;\n''','outer-observe-no-alias-gate')

once('''            if (context == null || account == null || folder == null || message == null ||\n                    message.id == null || account.uuid == null || message.deliveredto == null)\n                return;\n\n            SpamIntentObserver.start(context);\n            SpamFamilyRescorer.start(context);\n\n            AliasDomainAffinity.Evidence evidence = AliasDomainAffinity.fromMessage(context, message);\n            SpamAliasStore.observeDelivery(\n                    context,\n                    account.uuid,\n                    message.id,\n                    message.deliveredto,\n                    message.received,\n                    folder.type,\n                    evidence.senderDomain,\n                    evidence.unsubscribe);\n\n            refreshAssessment(context, account, message, true);\n            refreshFamilyMatch(context, account, message, true);\n            maybeAutoLabelExact(context, account, message);\n\n            AliasSenderManager.synchronizeForMessage(context, account, message);\n''','''            if (context == null || account == null || folder == null || message == null ||\n                    message.id == null || account.uuid == null)\n                return;\n\n            SpamIntentObserver.start(context);\n            SpamFamilyRescorer.start(context);\n\n            // Canonical message state always exists, even when Envelope-To was not retained.\n            SpamMessageStore.observe(context, account.uuid, message.id,\n                    message.received, folder.type, message.deliveredto);\n\n            if (message.deliveredto != null) {\n                AliasDomainAffinity.Evidence evidence = AliasDomainAffinity.fromMessage(context, message);\n                SpamAliasStore.observeDelivery(\n                        context,\n                        account.uuid,\n                        message.id,\n                        message.deliveredto,\n                        message.received,\n                        folder.type,\n                        evidence.senderDomain,\n                        evidence.unsubscribe);\n                refreshAssessment(context, account, message, true);\n                AliasSenderManager.synchronizeForMessage(context, account, message);\n            }\n\n            refreshMessageFamilyState(context, account, message, true);\n            maybeAutoLabelExact(context, account, message);\n''','inner-observe-message-first')

old='''            SpamIntelligenceDB intelligence = SpamIntelligenceDB.getInstance(context);\n            DaoAlias dao = intelligence.alias();\n\n            EntityAliasDelivery before = dao.getDelivery(account.uuid, message.id);\n            if (before == null && message.folder != null && message.deliveredto != null) {\n                EntityFolder folder = DB.getInstance(context).folder().getFolder(message.folder);\n                if (folder != null)\n                    observeMessage(context, account, folder, message);\n                before = dao.getDelivery(account.uuid, message.id);\n            }\n            if (before == null)\n                return;\n\n            Long familyId = requestedFamilyId;\n'''
new='''            SpamIntelligenceDB intelligence = SpamIntelligenceDB.getInstance(context);\n            DaoAlias dao = intelligence.alias();\n            DaoSpamMessage messageDao = intelligence.message();\n\n            EntitySpamMessage beforeMessage = messageDao.get(account.uuid, message.id);\n            if (beforeMessage == null && message.folder != null) {\n                EntityFolder folder = DB.getInstance(context).folder().getFolder(message.folder);\n                if (folder != null)\n                    SpamMessageStore.observe(context, account.uuid, message.id,\n                            message.received, folder.type, message.deliveredto);\n                beforeMessage = messageDao.get(account.uuid, message.id);\n            }\n            if (beforeMessage == null)\n                return;\n\n            EntityAliasDelivery beforeAlias = dao.getDelivery(account.uuid, message.id);\n\n            Long familyId = requestedFamilyId;\n'''
once(old,new,'setlabel-canonical-before')

once('''            boolean changed = SpamAliasStore.setLabel(\n                    context,\n                    account.uuid,\n                    message.id,\n                    label,\n                    familyId);\n            if (!changed) {\n                if (familyLearn != null && familyLearn.learned &&\n                        before.label != EntityAliasDelivery.LABEL_SPAM)\n                    SpamFamilyStore.unlearnMessage(\n                            context, account.uuid, message.id, familyLearn.familyId);\n                return;\n            }\n\n            Long changedFamily = null;\n            if (label == EntityAliasDelivery.LABEL_SPAM && familyId != null) {\n                SpamFamilyStore.reconcileFamily(context, familyId);\n                if (familyLearn != null && familyLearn.learned)\n                    changedFamily = familyId;\n            } else if (before.label == EntityAliasDelivery.LABEL_SPAM) {\n                changedFamily = SpamFamilyStore.unlearnMessage(\n                        context, account.uuid, message.id, before.family_id);\n            }\n''','''            boolean messageChanged = SpamMessageStore.setLabel(\n                    context, account.uuid, message.id, label, familyId);\n            boolean aliasChanged = beforeAlias != null && SpamAliasStore.setLabel(\n                    context, account.uuid, message.id, label, familyId);\n            if (!messageChanged && !aliasChanged) {\n                if (familyLearn != null && familyLearn.learned &&\n                        beforeMessage.label != EntitySpamMessage.LABEL_SPAM)\n                    SpamFamilyStore.unlearnMessage(\n                            context, account.uuid, message.id, familyLearn.familyId);\n                return;\n            }\n\n            Long changedFamily = null;\n            if (label == EntitySpamMessage.LABEL_SPAM && familyId != null) {\n                SpamFamilyStore.reconcileFamily(context, familyId);\n                if (familyLearn != null && familyLearn.learned)\n                    changedFamily = familyId;\n            } else if (beforeMessage.label == EntitySpamMessage.LABEL_SPAM) {\n                changedFamily = SpamFamilyStore.unlearnMessage(\n                        context, account.uuid, message.id, beforeMessage.family_id);\n            }\n''','setlabel-message-write')

once('''            EntityAliasDelivery after = dao.getDelivery(account.uuid, message.id);\n            if (after != null) {\n                if (label == EntityAliasDelivery.LABEL_SPAM) {\n''','''            EntityAliasDelivery after = dao.getDelivery(account.uuid, message.id);\n            if (after != null) {\n                if (label == EntitySpamMessage.LABEL_SPAM) {\n''','alias-sideeffect-label-constant')

once('''            refreshAssessment(context, account, message, false);\n            refreshFamilyMatch(context, account, message, false);\n''','''            if (after != null)\n                refreshAssessment(context, account, message, false);\n            refreshMessageFamilyState(context, account, message, false);\n''','post-label-refresh')

once('''    private static void refreshFamilyMatch(Context context,\n                                           EntityAccount account,\n                                           EntityMessage message,\n                                           boolean log) {\n''','''    public static void refreshMessageFamilyState(Context context,\n                                                 EntityAccount account,\n                                                 EntityMessage message,\n                                                 boolean log) {\n''','family-refresh-public')

# Replace the body-level DAO writes inside refreshMessageFamilyState.
once('''        DaoSpamFamily dao = SpamIntelligenceDB.getInstance(context).family();\n        long assessedAt = System.currentTimeMillis();\n        if (!SpamControlPolicy.exactFamilyDetection(context)) {\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n\n        SpamFamilyIdentity.Identity identity = SpamFamilyMessageAdapter.identityFromMessage(message);\n        if (identity == null) {\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n''','''        SpamIntelligenceDB intelligence = SpamIntelligenceDB.getInstance(context);\n        DaoSpamFamily dao = intelligence.family();\n        DaoSpamMessage messageDao = intelligence.message();\n        long assessedAt = System.currentTimeMillis();\n        if (!SpamControlPolicy.exactFamilyDetection(context)) {\n            messageDao.clearPrediction(account.uuid, message.id, assessedAt);\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n\n        SpamFamilyIdentity.Identity identity = SpamFamilyMessageAdapter.identityFromMessage(message);\n        if (identity == null) {\n            messageDao.clearPrediction(account.uuid, message.id, assessedAt);\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n''','family-refresh-message-dao')

once('''        if (match.familyId == null) {\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n\n        SpamFamilyEngine.Score score = match.score;\n        dao.setFamilyMatch(account.uuid, message.id, match.familyId,\n                score.value, score.raw, score.text, score.structure,\n                score.links, score.sender, assessedAt);\n''','''        if (match.familyId == null) {\n            messageDao.clearPrediction(account.uuid, message.id, assessedAt);\n            dao.clearFamilyMatch(account.uuid, message.id, assessedAt);\n            return;\n        }\n\n        SpamFamilyEngine.Score score = match.score;\n        messageDao.setPrediction(account.uuid, message.id, match.familyId,\n                score.value, assessedAt);\n        // Mirror into alias_delivery when that optional enrichment row exists.\n        dao.setFamilyMatch(account.uuid, message.id, match.familyId,\n                score.value, score.raw, score.text, score.structure,\n                score.links, score.sender, assessedAt);\n''','family-refresh-set-prediction')

once('''            EntityAliasDelivery delivery = SpamIntelligenceDB.getInstance(context)\n                    .alias().getDelivery(account.uuid, message.id);\n            if (delivery == null || delivery.label != EntityAliasDelivery.LABEL_UNKNOWN ||\n                    delivery.predicted_family_id == null)\n                return;\n            learnSpam(context, account, message, delivery.predicted_family_id);\n            Log.i("SpamControl auto-confirm exact family=" + delivery.predicted_family_id +\n                    " message=" + message.id);\n''','''            EntitySpamMessage state = SpamIntelligenceDB.getInstance(context)\n                    .message().get(account.uuid, message.id);\n            if (state == null || state.label != EntitySpamMessage.LABEL_UNKNOWN ||\n                    state.predicted_family_id == null)\n                return;\n            learnSpam(context, account, message, state.predicted_family_id);\n            Log.i("SpamControl auto-confirm exact family=" + state.predicted_family_id +\n                    " message=" + message.id);\n''','auto-label-message-state')

P.write_text(text)
print('patched SpamIntelligence for canonical message state')
