#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def replace_once(path, old, new):
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly 1 match, got {count}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")
    print(f"patched {path}")


# ---------- DaoAlias: paged UNKNOWN scan for exact bulk propagation ----------
replace_once(
    "app/src/main/java/eu/faircode/email/DaoAlias.java",
    '''    @Query("SELECT * FROM alias_delivery" +\n            " WHERE account_uuid = :accountUuid AND message_id = :messageId" +\n            " LIMIT 1")\n    EntityAliasDelivery getDelivery(String accountUuid, long messageId);\n\n    @Query("SELECT * FROM alias_delivery" +\n            " WHERE account_uuid = :accountUuid" +\n''',
    '''    @Query("SELECT * FROM alias_delivery" +\n            " WHERE account_uuid = :accountUuid AND message_id = :messageId" +\n            " LIMIT 1")\n    EntityAliasDelivery getDelivery(String accountUuid, long messageId);\n\n    @Query("SELECT * FROM alias_delivery" +\n            " WHERE account_uuid = :accountUuid" +\n            " AND label = " + EntityAliasDelivery.LABEL_UNKNOWN +\n            " AND message_id > :afterMessageId" +\n            " ORDER BY message_id" +\n            " LIMIT :limit")\n    List<EntityAliasDelivery> getUnknownDeliveriesAfter(\n            String accountUuid, long afterMessageId, int limit);\n\n    @Query("SELECT * FROM alias_delivery" +\n            " WHERE account_uuid = :accountUuid" +\n''')

# ---------- SpamLearningSnapshot: exact meta + full-account learning snapshots ----------
replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                root.put("families", familiesToJson(dao.getFamilies(account)));\n                root.put("exemplars", exemplarsToJson(dao.getExemplars(account)));\n                root.put("exclusions", exclusionsToJson(dao.getExclusions(account)));\n\n                if (messageId > 0) {\n''',
    '''                root.put("families", familiesToJson(dao.getFamilies(account)));\n                root.put("exemplars", exemplarsToJson(dao.getExemplars(account)));\n                root.put("exclusions", exclusionsToJson(dao.getExclusions(account)));\n                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n\n                if (messageId > 0) {\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''    static String captureAll(Context context) throws Exception {\n''',
    '''    /**\n     * Capture every learned row for one account. Used when one human action can\n     * legitimately update many exact-identity deliveries/aliases at once.\n     */\n    static String captureAccountAllLearning(Context context,\n                                            String accountUuid) throws Exception {\n        if (context == null || accountUuid == null || accountUuid.trim().isEmpty())\n            throw new IllegalArgumentException("accountUuid");\n\n        Context app = context.getApplicationContext();\n        SpamIntelligenceDB db = SpamIntelligenceDB.getInstance(app);\n        final String account = accountUuid.trim();\n        return db.runInTransaction(new Callable<String>() {\n            @Override\n            public String call() throws Exception {\n                DaoSpamSnapshot dao = db.snapshot();\n                JSONObject root = new JSONObject();\n                root.put("version", VERSION);\n                root.put("scope", SCOPE_ACCOUNT);\n                root.put("account_uuid", account);\n                root.put("message_id", 0L);\n                root.put("full_account_learning", true);\n                root.put("families", familiesToJson(dao.getFamilies(account)));\n                root.put("exemplars", exemplarsToJson(dao.getExemplars(account)));\n                root.put("exclusions", exclusionsToJson(dao.getExclusions(account)));\n                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.accountMetaPrefix(account))));\n\n                JSONArray deliveries = new JSONArray();\n                List<EntityAliasDelivery> deliveryRows = dao.getDeliveries(account);\n                if (deliveryRows != null)\n                    for (EntityAliasDelivery row : deliveryRows)\n                        if (row != null)\n                            deliveries.put(deliveryToJson(row));\n                root.put("deliveries", deliveries);\n\n                JSONArray aliases = new JSONArray();\n                List<EntityAlias> aliasRows = dao.getAliases(account);\n                if (aliasRows != null)\n                    for (EntityAlias row : aliasRows)\n                        if (row != null)\n                            aliases.put(aliasToJson(row));\n                root.put("aliases", aliases);\n                return encode(root);\n            }\n        });\n    }\n\n    static String captureAll(Context context) throws Exception {\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                root.put("families", familiesToJson(dao.getAllFamilies()));\n                root.put("exemplars", exemplarsToJson(dao.getAllExemplars()));\n                root.put("exclusions", exclusionsToJson(dao.getAllExclusions()));\n\n                JSONArray deliveries = new JSONArray();\n''',
    '''                root.put("families", familiesToJson(dao.getAllFamilies()));\n                root.put("exemplars", exemplarsToJson(dao.getAllExemplars()));\n                root.put("exclusions", exclusionsToJson(dao.getAllExclusions()));\n                root.put("meta", metaToJson(dao.getMetaByPrefix(\n                        SpamFamilyIdentity.globalMetaPrefix())));\n\n                JSONArray deliveries = new JSONArray();\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                    dao.deleteExemplars(account);\n                    dao.deleteFamilies(account);\n                    dao.clearPredictions(account);\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));\n                    List<EntitySpamFamilyExemplar> exemplars = exemplarsFromJson(root.getJSONArray("exemplars"));\n                    List<EntitySpamFamilyExclusion> exclusions = exclusionsFromJson(root.getJSONArray("exclusions"));\n                    if (!families.isEmpty())\n                        dao.putFamilies(families);\n                    if (!exemplars.isEmpty())\n                        dao.putExemplars(exemplars);\n                    if (!exclusions.isEmpty())\n                        dao.putExclusions(exclusions);\n\n                    JSONObject delivery = root.optJSONObject("delivery");\n                    if (delivery != null)\n                        restoreDelivery(dao, delivery);\n                    JSONObject alias = root.optJSONObject("alias");\n                    if (alias != null)\n                        restoreAlias(dao, alias);\n''',
    '''                    dao.deleteExemplars(account);\n                    dao.deleteFamilies(account);\n                    dao.clearPredictions(account);\n                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.accountMetaPrefix(account));\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));\n                    List<EntitySpamFamilyExemplar> exemplars = exemplarsFromJson(root.getJSONArray("exemplars"));\n                    List<EntitySpamFamilyExclusion> exclusions = exclusionsFromJson(root.getJSONArray("exclusions"));\n                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n                    if (!families.isEmpty())\n                        dao.putFamilies(families);\n                    if (!exemplars.isEmpty())\n                        dao.putExemplars(exemplars);\n                    if (!exclusions.isEmpty())\n                        dao.putExclusions(exclusions);\n                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n\n                    if (root.optBoolean("full_account_learning", false)) {\n                        dao.resetAccountDeliveryLearning(account);\n                        dao.resetAccountAliasLearning(account);\n\n                        JSONArray deliveries = root.optJSONArray("deliveries");\n                        if (deliveries != null)\n                            for (int i = 0; i < deliveries.length(); i++)\n                                restoreDelivery(dao, deliveries.getJSONObject(i));\n\n                        JSONArray aliases = root.optJSONArray("aliases");\n                        if (aliases != null)\n                            for (int i = 0; i < aliases.length(); i++)\n                                restoreAlias(dao, aliases.getJSONObject(i));\n                    } else {\n                        JSONObject delivery = root.optJSONObject("delivery");\n                        if (delivery != null)\n                            restoreDelivery(dao, delivery);\n                        JSONObject alias = root.optJSONObject("alias");\n                        if (alias != null)\n                            restoreAlias(dao, alias);\n                    }\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                    dao.deleteAllExemplars();\n                    dao.deleteAllFamilies();\n                    dao.resetAllDeliveryLearning();\n                    dao.resetAllAliasLearning();\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));\n                    List<EntitySpamFamilyExemplar> exemplars = exemplarsFromJson(root.getJSONArray("exemplars"));\n                    List<EntitySpamFamilyExclusion> exclusions = exclusionsFromJson(root.getJSONArray("exclusions"));\n''',
    '''                    dao.deleteAllExemplars();\n                    dao.deleteAllFamilies();\n                    if (root.has("meta"))\n                        dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                    dao.resetAllDeliveryLearning();\n                    dao.resetAllAliasLearning();\n\n                    List<EntitySpamFamily> families = familiesFromJson(root.getJSONArray("families"));\n                    List<EntitySpamFamilyExemplar> exemplars = exemplarsFromJson(root.getJSONArray("exemplars"));\n                    List<EntitySpamFamilyExclusion> exclusions = exclusionsFromJson(root.getJSONArray("exclusions"));\n                    List<EntitySpamMeta> meta = root.has("meta")\n                            ? metaFromJson(root.getJSONArray("meta"))\n                            : new ArrayList<EntitySpamMeta>();\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                    if (!exclusions.isEmpty())\n                        dao.putExclusions(exclusions);\n\n                    JSONArray deliveries = root.getJSONArray("deliveries");\n''',
    '''                    if (!exclusions.isEmpty())\n                        dao.putExclusions(exclusions);\n                    if (!meta.isEmpty())\n                        dao.putMeta(meta);\n\n                    JSONArray deliveries = root.getJSONArray("deliveries");\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''                dao.deleteAllExemplars();\n                dao.deleteAllFamilies();\n                dao.resetAllDeliveryLearning();\n                dao.resetAllAliasLearning();\n''',
    '''                dao.deleteAllExemplars();\n                dao.deleteAllFamilies();\n                dao.deleteMetaByPrefix(SpamFamilyIdentity.globalMetaPrefix());\n                dao.resetAllDeliveryLearning();\n                dao.resetAllAliasLearning();\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamLearningSnapshot.java",
    '''    private static JSONArray familiesToJson(List<EntitySpamFamily> rows) throws Exception {\n''',
    '''    private static JSONArray metaToJson(List<EntitySpamMeta> rows) throws Exception {\n        JSONArray result = new JSONArray();\n        if (rows == null)\n            return result;\n        for (EntitySpamMeta row : rows) {\n            if (row == null)\n                continue;\n            JSONObject o = new JSONObject();\n            o.put("key", row.key);\n            put(o, "long_value", row.long_value);\n            put(o, "text_value", row.text_value);\n            result.put(o);\n        }\n        return result;\n    }\n\n    private static List<EntitySpamMeta> metaFromJson(JSONArray rows) throws Exception {\n        List<EntitySpamMeta> result = new ArrayList<>();\n        for (int i = 0; i < rows.length(); i++) {\n            JSONObject o = rows.getJSONObject(i);\n            EntitySpamMeta row = new EntitySpamMeta();\n            row.key = o.getString("key");\n            row.long_value = optLong(o, "long_value");\n            row.text_value = optString(o, "text_value");\n            result.add(row);\n        }\n        return result;\n    }\n\n    private static JSONArray familiesToJson(List<EntitySpamFamily> rows) throws Exception {\n''')

# ---------- SpamUndoManager: account-wide reversible bulk action ----------
replace_once(
    "app/src/main/java/eu/faircode/email/SpamUndoManager.java",
    '''    public static boolean renameFamily(Context context,\n''',
    '''    public static SpamFamilyLabRepository.BulkActionResult runBulkMessageAction(\n            Context context,\n            String accountUuid,\n            long contextFamilyId,\n            long messageId,\n            String action,\n            String description,\n            Callable<SpamFamilyLabRepository.BulkActionResult> delegate) {\n        if (context == null || accountUuid == null || accountUuid.trim().isEmpty() ||\n                messageId <= 0 || delegate == null)\n            return SpamFamilyLabRepository.BulkActionResult.rejected();\n\n        Context app = context.getApplicationContext();\n        SpamIntelligenceDB db = SpamIntelligenceDB.getInstance(app);\n        Long historyId = null;\n        try {\n            String before = SpamLearningSnapshot.captureAccountAllLearning(\n                    app, accountUuid.trim());\n            historyId = recordBefore(db, accountUuid.trim(), messageId,\n                    contextFamilyId, action, description, before);\n\n            SpamFamilyLabRepository.BulkActionResult result = delegate.call();\n            if (result == null || result.result != SpamFamilyLabRepository.ActionResult.APPLIED)\n                db.actions().delete(historyId);\n            return result == null\n                    ? SpamFamilyLabRepository.BulkActionResult.rejected()\n                    : result;\n        } catch (Throwable ex) {\n            Log.e(ex);\n            if (historyId != null)\n                db.actions().delete(historyId);\n            return SpamFamilyLabRepository.BulkActionResult.rejected();\n        }\n    }\n\n    public static boolean renameFamily(Context context,\n''')

# ---------- Repository: one human Spam decision propagates exact identity ----------
replace_once(
    "app/src/main/java/eu/faircode/email/SpamFamilyLabRepository.java",
    '''    public enum ActionResult {\n        APPLIED,\n        MESSAGE_MISSING,\n        ACCOUNT_MISMATCH,\n        FAMILY_MISSING,\n        REJECTED\n    }\n\n    private SpamFamilyLabRepository() {\n''',
    '''    public enum ActionResult {\n        APPLIED,\n        MESSAGE_MISSING,\n        ACCOUNT_MISMATCH,\n        FAMILY_MISSING,\n        REJECTED\n    }\n\n    public static final class BulkActionResult {\n        public final ActionResult result;\n        public final int messages;\n        public final int aliases;\n\n        BulkActionResult(ActionResult result, int messages, int aliases) {\n            this.result = result == null ? ActionResult.REJECTED : result;\n            this.messages = Math.max(0, messages);\n            this.aliases = Math.max(0, aliases);\n        }\n\n        public static BulkActionResult rejected() {\n            return new BulkActionResult(ActionResult.REJECTED, 0, 0);\n        }\n\n        static BulkActionResult error(ActionResult result) {\n            return new BulkActionResult(result, 0, 0);\n        }\n    }\n\n    private SpamFamilyLabRepository() {\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamFamilyLabRepository.java",
    '''    /** Explicitly confirm this locally available message as spam in this exact group. */\n''',
    '''    /**\n     * One human Spam decision means the exact sender-name + subject identity is\n     * spam. Apply that truth to every retained UNKNOWN twin while preserving\n     * explicit HAM exceptions.\n     */\n    public static BulkActionResult markSpamBulk(Context context,\n                                                String accountUuid,\n                                                long messageId) {\n        Resolved resolved = resolve(context, accountUuid, messageId);\n        if (resolved.result != null)\n            return BulkActionResult.error(resolved.result);\n\n        SpamIntelligence.learnSpam(context, resolved.account, resolved.message, null);\n        DaoAlias aliasDao = SpamIntelligenceDB.getInstance(context).alias();\n        EntityAliasDelivery after = aliasDao.getDelivery(resolved.account.uuid, messageId);\n        if (after == null || after.label != EntityAliasDelivery.LABEL_SPAM)\n            return BulkActionResult.rejected();\n\n        if (after.family_id == null)\n            return new BulkActionResult(ActionResult.APPLIED, 1, after.address == null ? 0 : 1);\n\n        SpamExactBulkPropagator.Result propagated = SpamExactBulkPropagator.propagate(\n                context, resolved.account, resolved.message, after.family_id, after.address);\n        int messages = Math.max(1, propagated.messages);\n        int aliases = Math.max(after.address == null ? 0 : 1, propagated.aliases);\n        return new BulkActionResult(ActionResult.APPLIED, messages, aliases);\n    }\n\n    /** Explicitly confirm this locally available message as spam in this exact group. */\n''')

# ---------- SpamIntelligence: compromise is derived separately from spam ----------
replace_once(
    "app/src/main/java/eu/faircode/email/SpamIntelligence.java",
    '''            EntityAliasDelivery after = dao.getDelivery(account.uuid, message.id);\n            if (after != null) {\n                if (label == EntityAliasDelivery.LABEL_SPAM) {\n                    if (SpamControlPolicy.markAliasCompromised(context))\n                        dao.markCompromised(account.uuid, after.address);\n                } else {\n                    EntityAlias alias = dao.getAlias(account.uuid, after.address);\n                    if (alias != null && alias.state == EntityAlias.STATE_COMPROMISED &&\n                            alias.spam_hits == 0)\n                        dao.setState(account.uuid, after.address, EntityAlias.STATE_ACTIVE);\n                }\n            }\n\n            refreshAssessment(context, account, message, false);\n''',
    '''            EntityAliasDelivery after = dao.getDelivery(account.uuid, message.id);\n            if (after != null) {\n                if (label == EntityAliasDelivery.LABEL_SPAM) {\n                    if (SpamControlPolicy.markAliasCompromised(context)) {\n                        AliasCompromisePolicy.Decision compromise =\n                                aliasCompromiseDecision(context, account, message);\n                        if (compromise == AliasCompromisePolicy.Decision.COMPROMISE)\n                            dao.markCompromised(account.uuid, after.address);\n                        else if (compromise == AliasCompromisePolicy.Decision.REVIEW)\n                            Log.i("SpamControl alias compromise needs review alias=" + after.address +\n                                    " message=" + message.id);\n                    }\n                } else {\n                    EntityAlias alias = dao.getAlias(account.uuid, after.address);\n                    if (alias != null && alias.state == EntityAlias.STATE_COMPROMISED &&\n                            alias.spam_hits == 0)\n                        dao.setState(account.uuid, after.address, EntityAlias.STATE_ACTIVE);\n                }\n            }\n\n            refreshAssessment(context, account, message, false);\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/SpamIntelligence.java",
    '''    private static String emailDomain(String address) {\n''',
    '''    private static AliasCompromisePolicy.Decision aliasCompromiseDecision(\n            Context context, EntityAccount account, EntityMessage message) {\n        AliasTrafficAnalyzer.Result traffic = AliasTrafficAnalyzer.assess(\n                context, account, message);\n        AliasCompromisePolicy.Input input = new AliasCompromisePolicy.Input();\n        input.explicitSpam = true;\n        input.trafficSuspicious = traffic.assessment.verdict ==\n                AliasTrafficScorer.Verdict.SUSPICIOUS;\n        input.senderKnown = traffic.senderDomain != null;\n        input.expectedContextKnown = traffic.serviceDomain != null ||\n                (traffic.trustedDomains != null && !traffic.trustedDomains.isEmpty());\n        input.expectedSenderMatch = traffic.senderDomain != null &&\n                ((traffic.serviceDomain != null &&\n                        traffic.senderDomain.equalsIgnoreCase(traffic.serviceDomain)) ||\n                        containsIgnoreCase(traffic.trustedDomains, traffic.senderDomain));\n        input.aliasHam = traffic.aliasHam;\n        return AliasCompromisePolicy.decide(input);\n    }\n\n    private static boolean containsIgnoreCase(java.util.List<String> values, String needle) {\n        if (values == null || needle == null)\n            return false;\n        for (String value : values)\n            if (needle.equalsIgnoreCase(value))\n                return true;\n        return false;\n    }\n\n    private static String emailDomain(String address) {\n''')

# ---------- Activity: use bulk undo/action and show impact ----------
replace_once(
    "app/src/main/java/eu/faircode/email/ActivitySpamControl.java",
    '''        executor.execute(() -> {\n            SpamFamilyLabRepository.ActionResult result = SpamUndoManager.runMessageAction(\n                    getApplicationContext(), account.uuid, familyContext, candidate.messageId,\n                    spam ? SpamUndoManager.ACTION_SPAM : SpamUndoManager.ACTION_NOT_SPAM,\n                    spam ? "Spam" : "Ikke spam",\n                    () -> spam\n                            ? SpamFamilyLabRepository.markSpam(getApplicationContext(), account.uuid, candidate.messageId)\n                            : SpamFamilyLabRepository.markLegitimate(getApplicationContext(), account.uuid, candidate.messageId));\n            runOnUiThread(() -> {\n                reviewActionRunning.set(false);\n                if (isFinishing() || isDestroyed())\n                    return;\n                if (!isSelected(account)) {\n                    if (section == Section.REVIEW)\n                        renderCurrent();\n                    return;\n                }\n                if (result == SpamFamilyLabRepository.ActionResult.APPLIED) {\n                    String text = spam ? "Lagret som spam." : "Lagret som ikke spam.";\n''',
    '''        executor.execute(() -> {\n            SpamFamilyLabRepository.ActionResult result;\n            int affectedMessages = 1;\n            int affectedAliases = candidate.alias == null ? 0 : 1;\n            if (spam) {\n                SpamFamilyLabRepository.BulkActionResult bulk =\n                        SpamUndoManager.runBulkMessageAction(\n                                getApplicationContext(), account.uuid, familyContext, candidate.messageId,\n                                SpamUndoManager.ACTION_SPAM, "Spam · eksakt identitet",\n                                () -> SpamFamilyLabRepository.markSpamBulk(\n                                        getApplicationContext(), account.uuid, candidate.messageId));\n                result = bulk.result;\n                affectedMessages = Math.max(1, bulk.messages);\n                affectedAliases = Math.max(affectedAliases, bulk.aliases);\n            } else {\n                result = SpamUndoManager.runMessageAction(\n                        getApplicationContext(), account.uuid, familyContext, candidate.messageId,\n                        SpamUndoManager.ACTION_NOT_SPAM, "Ikke spam",\n                        () -> SpamFamilyLabRepository.markLegitimate(\n                                getApplicationContext(), account.uuid, candidate.messageId));\n            }\n            final int impactMessages = affectedMessages;\n            final int impactAliases = affectedAliases;\n            runOnUiThread(() -> {\n                reviewActionRunning.set(false);\n                if (isFinishing() || isDestroyed())\n                    return;\n                if (!isSelected(account)) {\n                    if (section == Section.REVIEW)\n                        renderCurrent();\n                    return;\n                }\n                if (result == SpamFamilyLabRepository.ActionResult.APPLIED) {\n                    String text;\n                    if (spam && impactMessages > 1)\n                        text = "Spam lært · " + impactMessages + " meldinger · " +\n                                impactAliases + " aliaser oppdatert.";\n                    else\n                        text = spam ? "Lagret som spam." : "Lagret som ikke spam.";\n''')

replace_once(
    "app/src/main/java/eu/faircode/email/ActivitySpamControl.java",
    '''        llPage.addView(policyCheck("Spam kompromitterer alias",\n                "Et eksplisitt Spam-valg markerer mottakeraliaset som COMPROMISED.",\n''',
    '''        llPage.addView(policyCheck("Spam kan kompromittere alias",\n                "Spam og alias-lekkasje er separate sannheter. Fremmed/mistenkelig spam kan markere aliaset COMPROMISED; spam fra forventet tjenesteavsender gjør det ikke.",\n''')

print("P0 bulk/undo/compromise patch complete")
